# Generated by Django 5.0.4 on 2024-05-05 21:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uu_id", models.UUIDField(default=uuid.uuid4)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("release_date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[("movie", "Movie"), ("serie", "Series")],
                        default="Movie",
                        max_length=100,
                    ),
                ),
                (
                    "production_company",
                    models.CharField(default="Uknown", max_length=255),
                ),
                ("length", models.PositiveIntegerField()),
                ("image_card", models.ImageField(upload_to="movie_images/")),
                ("image_cover", models.ImageField(upload_to="movie_images/")),
                ("video", models.FileField(upload_to="movie_videos/")),
                ("movie_views", models.IntegerField(default=0)),
            ],
        ),
    ]
