# Generated by Django 5.0.4 on 2024-05-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="trailer_link",
            field=models.TextField(default="uknown"),
            preserve_default=False,
        ),
    ]
