# Generated by Django 5.0.4 on 2024-05-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_movie_trailer_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="type",
            field=models.CharField(
                choices=[
                    ("movie", "Movie"),
                    ("serie", "Series"),
                    ("special", "Special"),
                ],
                default="Movie",
                max_length=100,
            ),
        ),
    ]
