# Generated by Django 5.0.4 on 2024-05-07 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_movie_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_series",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_number", models.PositiveIntegerField()),
                ("poster", models.ImageField(upload_to="season_posters/")),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.movie"
                    ),
                ),
            ],
        ),
    ]
