# Generated by Django 5.0.4 on 2024-05-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_episode"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="episodes_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
