# Generated by Django 5.0.4 on 2024-05-07 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_season_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.movie"
            ),
        ),
    ]
